name: deploy to npm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: install angular
      run: | 
        npm install
        npm run build --prod --aot
        cd dist/ngx-route-highlighter
        ls
