name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: install angular
      run: | 
        npm install -g @angular/cli
        cd ngx-route-highlighter
        npm i
